name: Docker GHCR Workflow
on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker GHCR
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_AT }}
        run: |
          echo $GHCR_TOKEN | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/pfee-livlink/livlinkapitest:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/pfee-livlink/livlinkapitest:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-publish

    steps:
      - name: write ssh key to file
        run: |
          echo "${{ secrets.MASTER_SSH_KEY }}" > id_rsa
          chmod 400 id_rsa
      - name: Login to GHCR Docker
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_AT }}
          MASTER_SSH_USER: ${{ secrets.MASTER_SSH_USER }}
          MASTER_HOST: ${{ secrets.MASTER_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no -i id_rsa "${MASTER_SSH_USER}@${MASTER_HOST}" "echo $GHCR_TOKEN | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin"
      - name: Download and run image
        run: |
          ssh -o StrictHostKeyChecking=no -i id_rsa "${MASTER_SSH_USER}@${MASTER_HOST}" "echo Hello"
