name: 'tagged-release'

on:
  push:
    tags:
      - 'v*'

jobs:
  tagged-release:
    name: 'Tagged Release'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm run docs:generate
      - run: npm pack
      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          files: |
            liv-link-api-*.tgz
            doc/openapi.yml
            doc/redoc.html
